# Generated by Django 5.1.7 on 2025-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtask',
            name='server_type',
        ),
        migrations.AlterField(
            model_name='trainingtask',
            name='model_type',
            field=models.CharField(choices=[('yolov8n', 'YOLOv8n (Nano)'), ('yolov8s', 'YOLOv8s (Small)'), ('yolov8m', 'YOLOv8m (Medium)'), ('yolov8l', 'YOLOv8l (Large)'), ('yolov8x', 'YOLOv8x (Extra Large)')], max_length=50),
        ),
    ]
