# Generated by Django 5.1.7 on 2025-04-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_trainingtask_server_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingtask',
            old_name='user',
            new_name='owner',
        ),
    ]
