# Generated by Django 5.1.7 on 2025-04-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_user_trainingtask_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingtask',
            name='name_task',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
