# Generated by Django 5.1.7 on 2025-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_trainingtask_dataset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtask',
            name='celery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
