# Generated by Django 5.1.7 on 2025-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_inferencetask_prediction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencetask',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
